version: '3.9'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "5000:5000"
    volumes:
      - ./:/title2image
    working_dir: /title2image/src
    tty: true

  frontend:
    image: node:16-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./:/title2image
    working_dir: /title2image/frontend
    command: yarn start

  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: 
      RUNNER_NAME: Runner
      ACCESS_TOKEN: $ACCESS_TOKEN
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
