version: '3.9'

services:
  backend:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/web-app
    working_dir: /web-app/src
    tty: true

  frontend:
    image: node:16-bullseye
    ports:
      - "3000:3000"
    volumes:
      - ./:/web-app
    working_dir: /web-app/frontend
    command: yarn watch

  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/MrKren/react-flask-template
      RUNNER_NAME: Runner
      ACCESS_TOKEN: $ACCESS_TOKEN
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
